### ISSUE TITLE
Solving system of linear equations with complex numbers

### ISSUE THREAD

**Issue by 30kpl4y** [jiggzson/nerdamer#475]
Is there any way to solve a system of linear equations with complex numbers on it?

Have this string of 2 equations with 2 variables (**i1** and **i2**), being **'j'** the imaginary unit.

nerdamer.set("IMAGINARY",'j')
str = [
"6 * ( i1 ) + ( 1 / ( j * 31)) * ( i1 ) + 251* j * ( i1 - i2 ) = - 20" ,
"3 * ( i2 - 3 ) + ( 1 / ( j * 628)) * ( i2 ) + 314* j * ( i2 ) + 251* j * ( i2 - i1 ) = 10"
]

**Comment by jiggzson** [comment]
I'll look into this. Thanks.

**Comment by 30kpl4y** [comment]
That would be awesome. Thanks.

**Comment by jiggzson** [comment]
@30kpl4y, this should be fixed.

**Comment by 30kpl4y** [comment]
@jiggzson, still not working... even with simple equations like the following:

`const resul = ["2*X1 - 4*X2 + 2*i = 3","- 5*X1 + 8*X2*i - 4*i*X1= 2"]
const sol = nerdamer.solveEquations(resul);`
**Error: System must contain all linear equations!**

![submit_git](https://user-images.githubusercontent.com/52736640/62840016-a5d22700-bc8b-11e9-80e8-bf80a7b7f581.jpg)

**Comment by jiggzson** [comment]
Are you using the `dev` branch? I forgot to mention that.

**Comment by 30kpl4y** [comment]
I've just used the `dev` branch and I got no error message but the result is always wrong.
I thing it is not assuming **i** as imaginary number. 
Check this:
`0:Symbol {group: 8, value: "-3-4*X2+2*X1+2*i", multiplier: Frac, …}
group:8
imaginary:false
isInfinity:false
length:4`

**Comment by jiggzson** [comment]
@30kpl4y, give it another go. The answer might not be as neat as you'd expect but I think they're correct now. Let me know.

**Comment by 30kpl4y** [comment]
@jiggzson I think the main issue is solved. My only concern for now is how can I convert the real and imaginary part into an exponential notation. **Result below**
![SharedScreenshot](https://user-images.githubusercontent.com/52736640/62933655-9ac9e480-bdba-11e9-820a-e609ceb33c22.jpg)

Do you have any recomendation?

**Comment by jiggzson** [comment]
I believe what you're looking for is [this](https://nerdamer.com/functions/polarform.html). The problem is that it expects complex numbers to be simplified. Let me know how it works out for you.

**Comment by 30kpl4y** [comment]
@jiggzson no, it not it. I want to have less numbers on the result, like intead of having `i0 = 1.88121978290e-10*i + 0.0209999999` i want to have `i0 = 1.88e-10*i + 0.02`.

**Comment by jiggzson** [comment]
I see. Is what you're talking about what's being discussed in #330?
